spring:
  application:
    name: ms-password-recovery-service

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - name: mascotas-vault
              endpoint: https://mascotas.vault.azure.net/

  r2dbc:
    url: ${urlR2DBC}
    username: ${SQLuser}
    password: ${SQLpassword}

token:
  expiration: 10

logging:
  level:
    com.example.mspasswordrecoveryservice: DEBUG
    org.springframework.r2dbc: WARN
    com.azure.spring: DEBUG
    com.azure.security.keyvault: DEBUG
    com.azure.identity: DEBUG


